sudo: required
dist: trusty
language: node_js
env:
  - CXX=g++-4.8
cache:
  directories:
  - node_modules
  - bower_components
  - typings
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_install:
  - npm install
install:
  - npm run bower
  - npm run typings
  - npm run build
node_js:
  - "5.11"
notifications:
  email:
    recipients:
      - cooluhuru@gmail.com
    on_success: never
    on_failure: always